package com.eric.hyh.tools.download.internal.db.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "TaskDBInfo".
 */
@Entity(nameInDb = "TaskDBInfo")
public class TaskDBInfo {

    @Id(autoincrement = true)
    private Long id;

    @Property(nameInDb = "resKey")
    @Unique
    private String resKey;

    @Property(nameInDb = "url")
    private String url;

    @Property(nameInDb = "currentStatus")
    private Integer currentStatus;

    @Property(nameInDb = "progress")
    private Integer progress;

    @Property(nameInDb = "versionCode")
    private Integer versionCode;

    @Property(nameInDb = "responseCode")
    private Integer responseCode;

    @Property(nameInDb = "rangeNum")
    private Integer rangeNum;

    @Property(nameInDb = "totalSize")
    private Long totalSize;

    @Property(nameInDb = "currentSize")
    private Long currentSize;

    @Property(nameInDb = "timeMillis")
    private Long timeMillis;

    @Property(nameInDb = "packageName")
    private String packageName;

    @Property(nameInDb = "filePath")
    private String filePath;

    @Property(nameInDb = "wifiAutoRetry")
    private Boolean wifiAutoRetry;

    @Property(nameInDb = "tagStr")
    private String tagStr;

    @Property(nameInDb = "tagClassName")
    private String tagClassName;

    @Generated
    public TaskDBInfo() {
    }

    public TaskDBInfo(Long id) {
        this.id = id;
    }

    @Generated
    public TaskDBInfo(Long id, String resKey, String url, Integer currentStatus, Integer progress, Integer versionCode, Integer responseCode, Integer rangeNum, Long totalSize, Long currentSize, Long timeMillis, String packageName, String filePath, Boolean wifiAutoRetry, String tagStr, String tagClassName) {
        this.id = id;
        this.resKey = resKey;
        this.url = url;
        this.currentStatus = currentStatus;
        this.progress = progress;
        this.versionCode = versionCode;
        this.responseCode = responseCode;
        this.rangeNum = rangeNum;
        this.totalSize = totalSize;
        this.currentSize = currentSize;
        this.timeMillis = timeMillis;
        this.packageName = packageName;
        this.filePath = filePath;
        this.wifiAutoRetry = wifiAutoRetry;
        this.tagStr = tagStr;
        this.tagClassName = tagClassName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getResKey() {
        return resKey;
    }

    public void setResKey(String resKey) {
        this.resKey = resKey;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getCurrentStatus() {
        return currentStatus;
    }

    public void setCurrentStatus(Integer currentStatus) {
        this.currentStatus = currentStatus;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    public Integer getVersionCode() {
        return versionCode;
    }

    public void setVersionCode(Integer versionCode) {
        this.versionCode = versionCode;
    }

    public Integer getResponseCode() {
        return responseCode;
    }

    public void setResponseCode(Integer responseCode) {
        this.responseCode = responseCode;
    }

    public Integer getRangeNum() {
        return rangeNum;
    }

    public void setRangeNum(Integer rangeNum) {
        this.rangeNum = rangeNum;
    }

    public Long getTotalSize() {
        return totalSize;
    }

    public void setTotalSize(Long totalSize) {
        this.totalSize = totalSize;
    }

    public Long getCurrentSize() {
        return currentSize;
    }

    public void setCurrentSize(Long currentSize) {
        this.currentSize = currentSize;
    }

    public Long getTimeMillis() {
        return timeMillis;
    }

    public void setTimeMillis(Long timeMillis) {
        this.timeMillis = timeMillis;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Boolean getWifiAutoRetry() {
        return wifiAutoRetry;
    }

    public void setWifiAutoRetry(Boolean wifiAutoRetry) {
        this.wifiAutoRetry = wifiAutoRetry;
    }

    public String getTagStr() {
        return tagStr;
    }

    public void setTagStr(String tagStr) {
        this.tagStr = tagStr;
    }

    public String getTagClassName() {
        return tagClassName;
    }

    public void setTagClassName(String tagClassName) {
        this.tagClassName = tagClassName;
    }

}
