package com.eric.hyh.tools.download.internal.db.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "TASK_DBINFO".
 */
@Entity
public class TaskDBInfo {

    @Id(autoincrement = true)
    private Long id;

    @Unique
    private String resKey;
    private String url;
    private Integer currentStatus;
    private Integer progress;
    private Integer versionCode;
    private Integer responseCode;
    private Integer rangeNum;
    private Long totalSize;
    private Long currentSize;
    private Long time;
    private String packageName;
    private String filePath;
    private String expand;
    private Boolean wifiAutoRetry;
    private String tagJson;
    private String tagClassName;

    @Generated
    public TaskDBInfo() {
    }

    public TaskDBInfo(Long id) {
        this.id = id;
    }

    @Generated
    public TaskDBInfo(Long id, String resKey, String url, Integer currentStatus, Integer progress, Integer versionCode, Integer responseCode, Integer rangeNum, Long totalSize, Long currentSize, Long time, String packageName, String filePath, String expand, Boolean wifiAutoRetry, String tagJson, String tagClassName) {
        this.id = id;
        this.resKey = resKey;
        this.url = url;
        this.currentStatus = currentStatus;
        this.progress = progress;
        this.versionCode = versionCode;
        this.responseCode = responseCode;
        this.rangeNum = rangeNum;
        this.totalSize = totalSize;
        this.currentSize = currentSize;
        this.time = time;
        this.packageName = packageName;
        this.filePath = filePath;
        this.expand = expand;
        this.wifiAutoRetry = wifiAutoRetry;
        this.tagJson = tagJson;
        this.tagClassName = tagClassName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getResKey() {
        return resKey;
    }

    public void setResKey(String resKey) {
        this.resKey = resKey;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getCurrentStatus() {
        return currentStatus;
    }

    public void setCurrentStatus(Integer currentStatus) {
        this.currentStatus = currentStatus;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    public Integer getVersionCode() {
        return versionCode;
    }

    public void setVersionCode(Integer versionCode) {
        this.versionCode = versionCode;
    }

    public Integer getResponseCode() {
        return responseCode;
    }

    public void setResponseCode(Integer responseCode) {
        this.responseCode = responseCode;
    }

    public Integer getRangeNum() {
        return rangeNum;
    }

    public void setRangeNum(Integer rangeNum) {
        this.rangeNum = rangeNum;
    }

    public Long getTotalSize() {
        return totalSize;
    }

    public void setTotalSize(Long totalSize) {
        this.totalSize = totalSize;
    }

    public Long getCurrentSize() {
        return currentSize;
    }

    public void setCurrentSize(Long currentSize) {
        this.currentSize = currentSize;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getExpand() {
        return expand;
    }

    public void setExpand(String expand) {
        this.expand = expand;
    }

    public Boolean getWifiAutoRetry() {
        return wifiAutoRetry;
    }

    public void setWifiAutoRetry(Boolean wifiAutoRetry) {
        this.wifiAutoRetry = wifiAutoRetry;
    }

    public String getTagJson() {
        return tagJson;
    }

    public void setTagJson(String tagJson) {
        this.tagJson = tagJson;
    }

    public String getTagClassName() {
        return tagClassName;
    }

    public void setTagClassName(String tagClassName) {
        this.tagClassName = tagClassName;
    }

}
